---
repos:
  - repo: "https://github.com/bufbuild/buf"
    rev: "v1.6.0"
    hooks:
      - id: "buf-lint"
  - repo: "https://github.com/adrienverge/yamllint.git"
    rev: "v1.29.0"
    hooks:
      - id: "yamllint"
